[book]
authors = ["tanganke"]
language = "en"
multilingual = false
src = "src"
title = "Introduction to Factorio"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/tanganke/introduction-to-factorio/"
edit-url-template = "https://github.com/tanganke/introduction-to-factorio/edit/master/{path}"
